require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - "bin/*"
    - "db/schema.rb"
    - "vendor/**/*"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - "config/environments/*.rb"
    - "config/routes.rb"

Metrics/MethodLength:
  Max: 20

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Layout/LineLength:
  Max: 150

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/RaiseException:
  Enabled: true

RSpec/ExampleLength:
  Max: 10

RSpec/Focus:
  AutoCorrect: false

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/NestedGroups:
  Max: 4

Style/AndOr:
  EnforcedStyle: conditionals

Style/Documentation:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%i": "[]"
    "%I": "[]"
    "%w": "[]"
    "%W": "[]"

Style/SignalException:
  Enabled: true
  EnforcedStyle: semantic
