#!/bin/sh

# Install xcode CLI
xcode-select --install

# Install homebrew
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

# update hombrew
brew update
brew upgrade

# Install homebrew dependencies
brew install fzf # fuzzy search
brew install direnv # looks for .envrc file in each directory

brew install gpg # managing keys 
# Hack for gpg https://stackoverflow.com/questions/39494631/gpg-failed-to-sign-the-data-fatal-failed-to-write-commit-object-git-2-10-0
brew upgrade gnupg
brew link --overwrite gnupg
brew install pinentry-mac
echo "pinentry-program /usr/local/bin/pinentry-mac" >> ~/.gnupg/gpg-agent.conf
killall gpg-agent

brew install zsh # neat CLI
brew install gnu-sed # GNU based sed
brew install bash # install new version of bash
echo "enter recovery mode and run csrutil disable, restart run set_new_bash_as_default, enter recovery mode again and run csrutil enable"
brew install aspell # spell checker

sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" # oh-my-zsh

brew cask install iterm2 # install iterm2

brew install nodenv # install node_env

# Link config files to the root direcotry
[ -r .make_links ] && ./make_links

# Generate file with git aliases for zshrc
./bin/generate_git_aliases_for_zshrc

# Setup necessary entries to the config files
if [ -r ~/.zshrc ] 
then
	# initialize direnv in zshrc
	echo $'# direnv initialize\neval "$(direnv hook zsh)' >> ~/.zshrc

	# initialize nodenv in zshrc
	echo $'# nodenv initialize\neval "$(nodenv init -)"' >> ~/.zshrc

	# add git aliases
	sed -i '' -e '/^# Example aliases/a\
		[ -r ~/.zsh_git_aliases ] && . ~/.zsh_git_aliases' ~/.zshrc

	# source varables and path files in zshrc
	sed -i '' -e '1i \ 
		# Link file with paths \
		[ -r ~/.env_paths ] && . ~/.env_paths \
		# Link file with variables \
		[ -r ~/.env_variables ] && . ~/.env_variables \
		\' ~/.zshrc
else
	echo '.zshrc config file does not exist'
fi
