#!/bin/bash

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# aspell
[[ -s "${BASE_DIR}/.aspell.en.pws" ]] && ln -fsv ${BASE_DIR}/.aspell.en.pws ~

# git
[[ -s "${BASE_DIR}/.gitconfig" ]] && ln -fsv ${BASE_DIR}/.gitconfig ~
[[ -s "${BASE_DIR}/.gitignore" ]] && ln -fsv ${BASE_DIR}/.gitignore ~

# shell
[[ -s "${BASE_DIR}/.env_paths" ]] && ln -fsv ${BASE_DIR}/.env_paths ~
[[ -s "${BASE_DIR}/.env_variables" ]] && ln -fsv ${BASE_DIR}/.env_variables ~

[[ -s "${BASE_DIR}/.zsh/.functions" ]] && ln -fsv ${BASE_DIR}/.zsh/.functions ~
[[ -s "${BASE_DIR}/.zsh/.aliases" ]] && ln -fsv ${BASE_DIR}/.zsh/.aliases ~

[[ -s "${BASE_DIR}/bin" ]] && ln -sv ${BASE_DIR}/bin ~

# vim
[[ -s "${BASE_DIR}/.vimrc" ]] && ln -fsv ${BASE_DIR}/.vimrc ~
[[ -s "${BASE_DIR}/.ideavimrc" ]] && ln -fsv ${BASE_DIR}/.ideavimrc ~
[[ -s "${BASE_DIR}/.ideavimrc" ]] && ln -fsv ${BASE_DIR}/.ideavimrc ~/.idevimrc

[[ -s "${BASE_DIR}/.vim/colors" ]] && ln -fsv ${BASE_DIR}/.vim/colors ~/.vim
[[ -s "${BASE_DIR}/.vim/lib" ]] && ln -fsv ${BASE_DIR}/.vim/lib ~/.vim/lib

# nvim
[[ -s "${BASE_DIR}/.nvim" ]] && stow .nvim
[[ -s "${BASE_DIR}/.aspell.en.pws" ]] && ln -fsv ${BASE_DIR}/.aspell.en.pws ~/.en.utf-8.add

# utlis
[[ -s "${BASE_DIR}/.rubocop.yml" ]] && ln -fsv ${BASE_DIR}/.rubocop.yml ~
[[ -s "${BASE_DIR}/.irbrc" ]] && ln -fsv ${BASE_DIR}/.irbrc ~
