#!/bin/sh

function _camel_case_to_dash_case() {
       converted_string=$(echo -n $@ | sed 's/\(.\)\([A-Z]\)/\1-\2/g' | tr '[:upper:]' '[:lower:]')

       echo $converted_string
       echo -n $converted_string | pbcopy
}
