#!/bin/sh

function _convert_to_dash_case() {
  converted_string=$(ruby -e "text='$@'; puts text.gsub(/[ _]/, '-').gsub(/([a-z])([A-Z])/, '\1-\2').downcase.split('-').reject(&:empty?).join('-')")

  echo "$converted_string"
  echo -n $converted_string | pbcopy
}
