#!/bin/sh

function _dash_case_to_camel_case() {
	# ruby -e 'puts ARGV[0].split("-").map(&:capitalize).join' $@
	converted_string=$(text="$@" ruby -e 'puts ENV["text"].split("-").map(&:capitalize).join')

	echo $converted_string
	echo -n $converted_string | pbcopy
}
